Repository NRLMMD-GEOIPS/geoips_clavrx, pull requests merged in 2023-05, with the labels that each got.

#9 Add missing docstring to init file
  geoips_clavrx/plugins/modules/algorithms/cloud/__init__.py
Labels: documentation

#11 Update all colormaps to matplotlib family
  CHANGELOG_colormaps.rst
  geoips_clavrx/plugins/modules/colormaps/cmap_IR.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldFraction.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldHeight.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldHeightBase.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldHeightTop.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldMask.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldOpd.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldPhase.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldReff.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldTemp.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldType.py
Labels: breaking change

#14 Update formatting for new product YAMLs
  geoips_clavrx/plugins/yaml/products/abi.yaml
  geoips_clavrx/plugins/yaml/products/ahi.yaml
  pyproject.toml
Labels: breaking change

#10 updated geoips_clavrx test_scrips to adhere to new schema changes to geoips
  docs/source/releases/index.rst
  docs/source/releases/v1_10_0a2.rst
  geoips_clavrx/plugins/modules/algorithms/cloud/__init__.py
  geoips_clavrx/plugins/modules/colormaps/cmap_IR.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldFraction.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldHeight.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldHeightBase.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldHeightTop.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldMask.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldOpd.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldPhase.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldReff.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldTemp.py
  geoips_clavrx/plugins/modules/colormaps/cmap_cldType.py
  geoips_clavrx/plugins/yaml/products/abi.yaml
  geoips_clavrx/plugins/yaml/products/ahi.yaml
  pyproject.toml
  tests/scripts/abi_cldFraction.sh
  tests/scripts/ahi_Temp11p0.sh
  tests/scripts/ahi_Temp3p75.sh
  tests/scripts/ahi_cldFraction.sh
  tests/scripts/ahi_cldHeight.sh
  tests/scripts/ahi_cldHeightBase.sh
  tests/scripts/ahi_cldHeightTop.sh
  tests/scripts/ahi_cldMask.sh
  tests/scripts/ahi_cldOpd.sh
  tests/scripts/ahi_cldPhase.sh
  tests/scripts/ahi_cldReff.sh
  tests/scripts/ahi_cldTemp.sh
  tests/scripts/ahi_cldType.sh
  tests/test_all.sh
Labels: refactor

#20 Add test_data install instructions to README
  CHANGELOG.rst
  README.md
  docs/source/releases/v1_10_0a3.rst
Labels: documentation, installation

#21 Correct path to test_data_clavrx clone
  README.md
Labels: bug
